title: PEER
description: The Workshop on Processing and Evaluating Event Representations
baseurl: ""
url: https://peer-workshop.github.io/

copyright: null
indexing: true

plugins:
- jekyll-seo-tag
- jekyll-sitemap

permalink: pretty

exclude:
  - LICENSE
  - README.md
